name: UiPath Deploy Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install UiPath CLI
        run: |
          dotnet tool install --global UiPath.CLI.Windows

      - name: Add CLI to PATH
        run: |
          echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH

      - name: Verify CLI
        run: |
          uipcli --version

      # ✅ Pack
      - name: Pack
        run: |
          uipcli package pack ./myproject/Git_Deploy . --output ./output --version 1.0.${{ github.run_number }}

      # ✅ Deploy
      - name: Deploy
        run: |
          uipcli package deploy --path ./output https://cloud.uipath.com ${{ secrets.UIPATH_TENANT_NAME }} `
           -t ${{ secrets.UIPATH_PAT }} `
           -a ${{ secrets.UIPATH_ACCOUNT_NAME }} `
           -o ${{ secrets.UIPATH_FOLDER_NAME }} `
            --entryPointsPath "Main.xaml"
