name: UiPath Deploy Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: UiPath Pack
        uses: UiPath/pack@v2
        with:
          versionType: "AutoVersion"
          outputFolder: "output"

      - name: UiPath Deploy
        uses: UiPath/deploy@v2
        with:
          orchestratorUrl: https://cloud.uipath.com
          tenantName: ${{ secrets.UIPATH_TENANT_NAME }}
          folderName: ${{ secrets.UIPATH_FOLDER_NAME }}
          packagePath: "output"
          token: ${{ secrets.UIPATH_PAT }}
